"""Phase 8 — Multi-horizon calibration scaffold.

Phase 4.7 fits used `forward_return_60d` (60-day forward return)
as the single calibration target. This serves the medium-term
investor (~3 month horizon) but not:

  - SHORT-TERM TRADER (5-20 day swing): wants momentum + earnings-
    surprise reactions. PE / PB / ROIC don't move skor much in
    20 days — calibration learns flatter fits, signal dilutes.

  - LONG-TERM VALUE INVESTOR (250+ day, 1 year): fundamentals
    dominate. PE/PB skor much more sharply over a year — current
    60-day calibration understates the long-run pull.

Phase 8 produces 3 separate fits artifacts:

  reports/fa_isotonic_fits_20d.json   short-term trader
  reports/fa_isotonic_fits.json       60-day (current default)
  reports/fa_isotonic_fits_250d.json  long-term value

Dispatcher accepts ?horizon=20d|60d|250d query param routing to
the appropriate artifact.

THIS TURN: scaffold (horizon constants, path resolver, metric
key generator, dispatcher routing). Actual fits per horizon
generated by Phase 8 deploy Colab notebook.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

log = logging.getLogger("bistbull.scoring_calibrated_horizons")


# ==========================================================================
# Horizon constants
# ==========================================================================

# Standard horizons in business days
HORIZON_SHORT = "20d"   # ~1 month, swing trader
HORIZON_DEFAULT = "60d"  # ~3 months, current calibration
HORIZON_LONG = "250d"   # ~1 year, long-term value investor

SUPPORTED_HORIZONS: frozenset[str] = frozenset({
    HORIZON_SHORT, HORIZON_DEFAULT, HORIZON_LONG,
})


# ==========================================================================
# Per-horizon artifact paths
# ==========================================================================

_REPORTS_DIR = Path(__file__).resolve().parent.parent / "reports"

HORIZON_FITS_PATHS: dict[str, Path] = {
    HORIZON_SHORT:   _REPORTS_DIR / "fa_isotonic_fits_20d.json",
    HORIZON_DEFAULT: _REPORTS_DIR / "fa_isotonic_fits.json",
    HORIZON_LONG:    _REPORTS_DIR / "fa_isotonic_fits_250d.json",
}


def resolve_horizon_fits_path(horizon: str) -> Optional[Path]:
    """Map horizon string ('20d', '60d', '250d') → fits artifact path.

    Returns None for unknown horizons (caller should fall back to
    default or report error).
    """
    return HORIZON_FITS_PATHS.get(horizon)


def normalize_horizon(horizon: Optional[str]) -> str:
    """Normalize a user-supplied horizon string.

    - None / empty → DEFAULT (60d)
    - Any of the supported strings → returned as-is
    - Unknown → DEFAULT with a warning (defensive)
    """
    if not horizon:
        return HORIZON_DEFAULT
    h = horizon.strip().lower()
    if h in SUPPORTED_HORIZONS:
        return h
    log.warning(f"unknown horizon {horizon!r}, falling back to {HORIZON_DEFAULT}")
    return HORIZON_DEFAULT


# ==========================================================================
# Metric key generator (CSV column names)
# ==========================================================================

def horizon_target_key(horizon: str) -> str:
    """Return the CSV / events.csv column name for a horizon.

    'forward_return_20d', 'forward_return_60d', 'forward_return_250d'.
    """
    h = normalize_horizon(horizon)
    return f"forward_return_{h}"


# ==========================================================================
# Per-horizon fits loader
# ==========================================================================

def get_horizon_fits(
    horizon: str,
    force_reload: bool = False,
):
    """Load fits artifact for the requested horizon.

    Returns dict[metric, IsotonicFit] or None if artifact missing.
    Caller falls back to default horizon (60d) which has Phase 4.7
    real fits, then to V13 if even that's missing.
    """
    h = normalize_horizon(horizon)
    path = HORIZON_FITS_PATHS[h]

    from engine.scoring_calibrated import _get_fits, CALIBRATED_VERSION

    # Use a synthetic version key per horizon for cache isolation
    cache_version = f"{CALIBRATED_VERSION}_{h}"
    return _get_fits(
        fits_path=path,
        force_reload=force_reload,
        scoring_version=cache_version,
    )


# ==========================================================================
# Multi-horizon score_dispatch wrapper
# ==========================================================================

def score_dispatch_with_horizon(
    m: dict,
    sector_group: Optional[str] = None,
    scoring_version: Optional[str] = None,
    fits: Optional[dict] = None,
    symbol: Optional[str] = None,
    horizon: Optional[str] = None,
) -> dict:
    """Phase 8 wrapper that selects per-horizon fits before dispatching.

    Behaviour:
      - horizon=None → use default fits (Phase 4.7 60d), behaviour
        identical to score_dispatch
      - horizon='20d' or '250d' → load that horizon's fits and pass
        them in via the fits kwarg
      - if requested horizon's fits missing → fall back to 60d fits
      - if 60d fits also missing → V13 (existing fallback chain)

    Returns same shape as score_dispatch with an additional
    'horizon' field in the result for telemetry.
    """
    from engine.scoring_calibrated import (
        score_dispatch, CALIBRATED_VERSION, HANDPICKED_VERSION,
    )

    h = normalize_horizon(horizon)
    sv = scoring_version or HANDPICKED_VERSION

    # If horizon is non-default and a calibrated version is requested,
    # try to load that horizon's fits explicitly.
    horizon_fits = None
    if h != HORIZON_DEFAULT and sv == CALIBRATED_VERSION:
        horizon_fits = get_horizon_fits(h)
        if horizon_fits is None:
            log.info(
                f"horizon={h} fits not available; falling back to "
                f"{HORIZON_DEFAULT}"
            )
            h = HORIZON_DEFAULT

    # Pass through to base dispatcher (handles V13 fallback if even
    # default fits are missing).
    result = score_dispatch(
        m, sector_group=sector_group,
        scoring_version=sv,
        fits=fits if fits is not None else horizon_fits,
        symbol=symbol,
    )
    # Annotate with horizon for telemetry
    result["horizon"] = h
    return result
