export const STOCKS = [
  { ticker: "AKBNK", name: "Akbank", sector: "Banka" },
  { ticker: "ARCLK", name: "Arçelik", sector: "Dayanıklı Tüketim" },
  { ticker: "ASELS", name: "Aselsan", sector: "Savunma" },
  { ticker: "BIMAS", name: "BİM", sector: "Perakende" },
  { ticker: "DOHOL", name: "Doğan Holding", sector: "Holding" },
  { ticker: "EKGYO", name: "Emlak Konut GYO", sector: "GYO" },
  { ticker: "ENKAI", name: "Enka İnşaat", sector: "İnşaat" },
  { ticker: "EREGL", name: "Ereğli Demir Çelik", sector: "Metal" },
  { ticker: "FROTO", name: "Ford Otosan", sector: "Otomotiv" },
  { ticker: "GARAN", name: "Garanti BBVA", sector: "Banka" },
  { ticker: "GUBRF", name: "Gübre Fabrikaları", sector: "Kimya" },
  { ticker: "HEKTS", name: "Hektaş", sector: "Kimya" },
  { ticker: "ISCTR", name: "İş Bankası C", sector: "Banka" },
  { ticker: "KCHOL", name: "Koç Holding", sector: "Holding" },
  { ticker: "KONTR", name: "Kontrolmatik", sector: "Enerji" },
  { ticker: "KOZAA", name: "Koza Altın", sector: "Madencilik" },
  { ticker: "KOZAL", name: "Koza Madencilik", sector: "Madencilik" },
  { ticker: "KRDMD", name: "Kardemir D", sector: "Metal" },
  { ticker: "MGROS", name: "Migros", sector: "Perakende" },
  { ticker: "ODAS",  name: "Odaş Elektrik", sector: "Enerji" },
  { ticker: "OYAKC", name: "Oyak Çimento", sector: "Çimento" },
  { ticker: "PETKM", name: "Petkim", sector: "Kimya" },
  { ticker: "PGSUS", name: "Pegasus", sector: "Havacılık" },
  { ticker: "SAHOL", name: "Sabancı Holding", sector: "Holding" },
  { ticker: "SASA",  name: "SASA Polyester", sector: "Kimya" },
  { ticker: "SISE",  name: "Şişecam", sector: "Cam" },
  { ticker: "TAVHL", name: "TAV Havalimanları", sector: "Havacılık" },
  { ticker: "TCELL", name: "Turkcell", sector: "Telekom" },
  { ticker: "THYAO", name: "THY", sector: "Havacılık" },
  { ticker: "TOASO", name: "Tofaş", sector: "Otomotiv" },
  { ticker: "TUPRS", name: "Tüpraş", sector: "Enerji" },
  { ticker: "YKBNK", name: "Yapı Kredi", sector: "Banka" },
  { ticker: "AEFES", name: "Anadolu Efes", sector: "İçecek" },
  { ticker: "AKSA",  name: "Aksa Akrilik", sector: "Kimya" },
  { ticker: "TTKOM", name: "Türk Telekom", sector: "Telekom" },
  { ticker: "VESTL", name: "Vestel", sector: "Elektronik" },
  { ticker: "AGHOL", name: "Ağaoğlu Holding", sector: "Holding" },
  { ticker: "CIMSA", name: "Çimsa", sector: "Çimento" },
  { ticker: "DOAS",  name: "Doğuş Otomotiv", sector: "Otomotiv" },
  { ticker: "TTRAK", name: "Türk Traktör", sector: "Otomotiv" },
];

export const SECTORS = [...new Set(STOCKS.map(s => s.sector))];

export const MARKET_INSTRUMENTS = [
  { id: "xu030", label: "XU030", type: "index" },
  { id: "usdtry", label: "USD/TRY", type: "fx" },
  { id: "eurtry", label: "EUR/TRY", type: "fx" },
  { id: "brent", label: "BRENT", type: "commodity" },
  { id: "gold", label: "ALTIN", type: "commodity" },
  { id: "xbank", label: "XBANK", type: "index" },
];

export const CROSS_TYPES = [
  { id: "ema5_20", label: "EMA 5/20", desc: "Kısa vade momentum" },
  { id: "ema20_50", label: "EMA 20/50", desc: "Orta vade trend" },
  { id: "ema50_200", label: "EMA 50/200", desc: "Golden/Death Cross" },
  { id: "rsi_30", label: "RSI < 30", desc: "Aşırı satım çıkışı" },
  { id: "rsi_70", label: "RSI > 70", desc: "Aşırı alım girişi" },
  { id: "macd_cross", label: "MACD Cross", desc: "MACD sinyal kesişimi" },
];
