#!/usr/bin/env python3
"""Discover the actual DataFrame.index labels borsapy returns for
Turkish KAP quarterly statements.

CONTEXT (Phase 4.7 v2):
  Colab ROUND-A ingest produced only 3 of 25 expected metrics because
  the hardcoded Turkish candidate labels in ingest_fa_for_calibration.py
  didn't match what borsapy actually returns. This script is the
  round-trip fix: run it in Colab first, get the real labels, update
  the ingest script's candidate lists with ground-truth strings.

USAGE (Colab):
    !python scripts/explore_borsapy_labels.py > reports/borsapy_label_discovery.md

The output is a readable Markdown file the agent can consume to update
ingest label candidates.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Repo path
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Sample 5 symbols spanning non-bank sectors.
# Banks deliberately excluded — they have a totally different
# schema ("Krediler", "Bankalar Bakiyeleri" etc.) and are
# handled in a future Phase 5 calibration pass.
SAMPLE_SYMBOLS: list[str] = [
    "THYAO",  # Havayolu (airlines)
    "ASELS",  # Savunma (defense)
    "EREGL",  # Demir-Çelik (steel)
    "BIMAS",  # Perakende (retail)
    "TUPRS",  # Enerji (energy / refining)
]


def _print_md(s: str = "") -> None:
    print(s, flush=True)


def _discover_one_symbol(bp_module, symbol: str) -> None:
    _print_md(f"## {symbol}")
    try:
        tk = bp_module.Ticker(symbol)
    except Exception as e:
        _print_md(f"**ERROR constructing Ticker:** {type(e).__name__}: {e!r}")
        _print_md()
        return

    for statement_name, getter, extra_kwargs in [
        ("income_stmt",   "get_income_stmt",   {}),
        ("balance_sheet", "get_balance_sheet", {}),
        ("cashflow",      "get_cashflow",      {}),
    ]:
        _print_md(f"### {statement_name}")
        try:
            df = getattr(tk, getter)(
                quarterly=True,
                financial_group=None,
                last_n=4,  # just 1 year of columns — we only want the labels
                **extra_kwargs,
            )
        except Exception as e:
            _print_md(
                f"**ERROR from {getter}():** "
                f"{type(e).__name__}: {e!r}"
            )
            _print_md()
            continue

        if df is None:
            _print_md("_(None returned)_")
            _print_md()
            continue

        try:
            import pandas as pd
            if not isinstance(df, pd.DataFrame):
                _print_md(f"_(not a DataFrame; type={type(df).__name__})_")
                _print_md()
                continue
            if df.empty:
                _print_md("_(empty DataFrame)_")
                _print_md()
                continue

            _print_md(f"- shape: {df.shape}")
            _print_md(f"- columns (period_ends): {list(df.columns)}")
            _print_md(f"- index (labels): {df.index.nunique()} unique")
            _print_md()
            _print_md("```")
            for label in df.index.tolist():
                _print_md(f"  {label!r}")
            _print_md("```")
        except Exception as e:
            _print_md(f"**ERROR inspecting DataFrame:** {type(e).__name__}: {e!r}")
        _print_md()


def main() -> int:
    _print_md("# borsapy Label Discovery — Phase 4.7 v2 ROUND A")
    _print_md()
    _print_md("Generated by `scripts/explore_borsapy_labels.py` in Colab. "
              "Used by the agent to update candidate labels in "
              "`scripts/ingest_fa_for_calibration.py`.")
    _print_md()
    _print_md(f"Symbols sampled: {SAMPLE_SYMBOLS}")
    _print_md()

    try:
        import borsapy as bp
    except ImportError as e:
        _print_md(f"**FATAL: borsapy not importable:** {e!r}")
        _print_md()
        _print_md("Run `!pip install -q borsapy` first.")
        return 2

    for sym in SAMPLE_SYMBOLS:
        _discover_one_symbol(bp, sym)

    _print_md("---")
    _print_md()
    _print_md("## Label normalization reference")
    _print_md()
    _print_md("When updating `scripts/ingest_fa_for_calibration.py`, use the "
              "EXACT labels above as candidate strings. The script's "
              "`pick_value()` helper normalizes via "
              "`utils/label_matching.normalize_label`, so minor diacritic "
              "or whitespace differences are forgiven. But try to copy labels "
              "verbatim for the least ambiguity.")
    _print_md()
    _print_md("Expected fields + candidate labels should cover these 13 "
              "metrics (per `scripts/ingest_fa_for_calibration.py:"
              "METRIC_REGISTRY`):")
    _print_md()
    _print_md("| Metric | Source statement | Expected KAP label |")
    _print_md("|---|---|---|")
    _print_md("| revenue           | income   | Hasılat, Satış Gelirleri |")
    _print_md("| gross_profit      | income   | Brüt Kar, Brüt Kar/Zarar |")
    _print_md("| operating_income  | income   | Esas Faaliyet Karı, Faaliyet Karı |")
    _print_md("| net_income        | income   | Dönem Net Karı, Ana Ortaklığa Ait |")
    _print_md("| ebit              | income   | FAVÖK, Faaliyet Karı |")
    _print_md("| interest_expense  | income   | Finansman Giderleri, Faiz Giderleri |")
    _print_md("| equity            | balance  | Özkaynaklar, Toplam Özkaynaklar |")
    _print_md("| total_debt        | balance  | Toplam Finansal Borçlar |")
    _print_md("| cash              | balance  | Nakit ve Nakit Benzerleri |")
    _print_md("| current_assets    | balance  | Dönen Varlıklar |")
    _print_md("| current_liab      | balance  | Kısa Vadeli Yükümlülükler |")
    _print_md("| total_assets      | balance  | Toplam Varlıklar, Aktifler |")
    _print_md("| free_cashflow     | cashflow | Serbest Nakit Akışı |")
    _print_md("| operating_cf      | cashflow | İşletme Faaliyetlerinden... |")
    return 0


if __name__ == "__main__":
    sys.exit(main())
